apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentaire
spec:
  selector:
    matchLabels:
      app: commentaire
  template:
    metadata:
      labels:
        app: commentaire
    spec:
      containers:
      - name: commentaire
        image: loico16/commentaire:v6
        ports:
        - containerPort: 3006