apiVersion: v1
kind: Service
metadata:
  name: commentaire-lb
spec:
  selector:
    app: commentaire
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  nodePort: 30006
