apiVersion: apps/v1
kind: Deployment
metadata:
  name: urgence
spec:
  selector:
    matchLabels:
      app: urgence
  template:
    metadata:
      labels:
        app: urgence
    spec:
      containers:
      - name: urgence
        image: loico16/urgence:v4
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      