apiVersion: apps/v1
kind: Deployment
metadata:
  name: urgence-deployment
spec:
  selector:
    matchLabels:
      app: urgences
  template:
    metadata:
      labels:
        app: urgences
    spec:
      containers:
      - name: urgences
        image: loico16/urgence:v1
        ports:
        - containerPort: 3000