apiVersion: v1
kind: Service
metadata:
  name: auth-lb
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  nodePort: 30005
